// test file to see if everything is working
import fs from "fs";

/*
class Parent {
public:
    Parent(string name, int age) {
        this:name = name;
        this:age = age;
    }
    ~Parent() = default;

    static fn int get() {
        return rand();
    }

private:
    string name;
    int age;
}
*/

fn int square(int n) {
    return n*n;
}

fn void main() {
    // Parent p("John", 23);
    // print("%d", Parent::get());
    
}


test_begin
mo/*
smc//*/
mos/*//
mc*/
mosmc/*//*/
test_end

a
/*/
b